### ISSUE TITLE
Cube three support? 

### ISSUE THREAD

**Issue by TheNewsYorkTime** [mirdoc/Cura-CubePrinterPlugin#1]
Does this support the Cube 3? I've heard of a converter between the cubepro and cube files I think. It's been a while though.

**Comment by mirdoc** [comment]
Due to popular demand support added for not only Cube 3 but also Cube, Cube 2, and Cube X.  I don't have the ability to test these printers though so I don't know how well it will work, but please do try it out and report back if you have any issues or suggestions.

**Comment by TheNewsYorkTime** [comment]
Thank you!
