### ISSUE TITLE
Cube 3 bugs when print starts

### ISSUE THREAD

**Issue by javinnieto** [mirdoc/Cura-CubePrinterPlugin#2]
Hello Mirdoc. First of all, I love this project. It is truly huge work.

My cube 3 has a bug when starts the print. Every axis starts to move and the don't stop. So, when they goes to the end, you can hear this horrible noise like something is crashing. 
I decode the .cube3 file to .bfb and I realize the line that has the problem is the one that doesn't have all predefined parameters x, y and z. It turns out .gcode files doesn't really need every parameter, but cube3 (as far as I am concerned) does.

So I Fixed it just adding this at line 219 in plugins-> CubePrinterPlugin-> CubeproWriter-> CubeproWriter.py :

`elif line[0] == "G" and "Z" not in line:
                continue #Every motion command (G) needs x, y and z parameter to work. So it just skips when find a line that doesn't have Z.
            # This line fixes cube3 bug  `

**Comment by javinnieto** [comment]
Skiping this line doesn't really affect the print because it is just the first or the two first motion lines (G) that have this issue.

**Comment by mirdoc** [comment]
Thanks Javi!  I think this is actually all my fault as the lines without Z are, I think, from the extruder start gcode which is defined for each extruder in the printer settings.  I put some gcode in there from a .cube3 that I decoded but noticed the Z would have to change if there was an extruder change later in the print so I just left it out. I was of the understanding that not all coords were required per G1 but as you say apparently not for the Cube 3!  

What I might do is capture the coords from each move and add it to any subsequent move where there are any coords missing, just to handle any situations where they really are needed.  

This is obviously pretty critical so I'll push through an update and release a new curapackage in the next hour or two.

**Comment by mirdoc** [comment]
As above this (hopefully) has been addressed in Release 0.2.2 which has just been published.

Thanks again for your help!

**Comment by javinnieto** [comment]
Thank you!!
