### ISSUE TITLE
Cube3 Extruder properties error

### ISSUE THREAD

**Issue by gberube05** [mirdoc/Cura-CubePrinterPlugin#3]
Error in loading in all the files causing an issue with loading a cube3 as a printer, seems to be with the extruder properties. 
![Capture](https://github.com/mirdoc/Cura-CubePrinterPlugin/assets/162063798/071c0054-0012-42ea-8f36-7a99891c27ec)

cubePro printer loaded in as normal.

Win10 x64. issue was also present on macOS Big Sur
![Capture](https://github.com/mirdoc/Cura-CubePrinterPlugin/assets/162063798/6e2b42d3-382d-4d2c-89d2-e445225f372c)

**Comment by javinnieto** [comment]
Yes, I have the same issue on Windows. I tried to delete cube3_extruder_0.def.json and create a new one, but every time you open Cura, this file is created by the plugin. 
I think it's not a code bug, but the file it self, it is corrupted.

**Comment by gberube05** [comment]
File corruption makes the most sense. Maybe there was an error uploading the plugin?

**Comment by mirdoc** [comment]
Sorry guys, I didn't test the curapackage before releasing it. My bad!

You are correct the curapackage was somehow corrupted so I have rebuilt it and tested it and it seems to be working fine now.  

I will re-release it as 0.2.3 to hopefully allow you to upgrade and fix this problem.  If for some reason Cura continues to report a configuration error click the Reset button and reinstall the curapackage.

Let me know if this solves the issue and I can close this.

Thanks again for being understanding testers 🥇

**Comment by gberube05** [comment]
Loaded fine now. Im starting a benchy print at baseline settings. Ill update the FaceBook page with results!

**Comment by javinnieto** [comment]
It works fine. Thanks Mirdoc!

**Comment by mirdoc** [comment]
Great!
